"""Domain models for AI Quant Scientist."""

from .evaluation import EvaluationDecision, EvaluationReasonCode, EvaluationRecommendation, ResultEvaluationPolicy
from .enums import ResearchStage, RunStatus, ResearchAction, SpecRevisionProposalStatus
from .design import (
    AnalysisIntent,
    ComparisonIntent,
    ConditionExecutionRecord,
    ConditionExecutionStatus,
    DesignOutcome,
    DesignVariable,
    ExperimentCondition,
    ExperimentConditionRole,
    InitialExperimentCompletionRule,
    InitialExperimentPlan,
    InitialExperimentPlanMaterializationResult,
    InitialExperimentPlanProposal,
    InitialExperimentPlanProposalStatus,
    OutcomeContrast,
    ParameterSensitivityContrastResult,
    ResearchDesignIntent,
    ResearchDesignKind,
    SpecFeasibilityDecision,
    SpecFeasibilityPhase,
    SpecFeasibilityReasonCode,
    SpecFeasibilityStatus,
    SpecMaterializationProposal,
    SpecMaterializationProposalStatus,
    SpecMaterializationResult,
)
from .research import AuditEvent, ExperimentResult, Hypothesis, ResearchAttempt, ResearchRun, ResearchSpec, SpecRevisionProposal
from .critic import CriticContext, CriticDecision, CriticInvocation, CriticDecisionType

__all__ = [
    "AnalysisIntent",
    "AuditEvent",
    "ComparisonIntent",
    "ConditionExecutionRecord",
    "ConditionExecutionStatus",
    "EvaluationDecision",
    "EvaluationReasonCode",
    "EvaluationRecommendation",
    "DesignOutcome",
    "DesignVariable",
    "ExperimentCondition",
    "ExperimentConditionRole",
    "ExperimentResult",
    "Hypothesis",
    "InitialExperimentCompletionRule",
    "InitialExperimentPlan",
    "InitialExperimentPlanMaterializationResult",
    "InitialExperimentPlanProposal",
    "InitialExperimentPlanProposalStatus",
    "OutcomeContrast",
    "ParameterSensitivityContrastResult",
    "ResearchDesignIntent",
    "ResearchDesignKind",
    "ResearchAttempt",
    "ResearchRun",
    "ResearchSpec",
    "SpecRevisionProposal",
    "SpecFeasibilityDecision",
    "SpecFeasibilityPhase",
    "SpecFeasibilityReasonCode",
    "SpecFeasibilityStatus",
    "SpecMaterializationProposal",
    "SpecMaterializationProposalStatus",
    "SpecMaterializationResult",
    "CriticContext",
    "CriticDecision",
    "CriticInvocation",
    "CriticDecisionType",
    "ResultEvaluationPolicy",
    "ResearchStage",
    "RunStatus",
    "ResearchAction",
    "SpecRevisionProposalStatus",
]
